service: lambda-webhook

provider:
  name: aws
  runtime: python3.11
  environment:
    TWILIO_AUTH: ${env:TWILIO_AUTH}

plugins:
  - serverless-wsgi
  - serverless-python-requirements

functions:
  webhook:
    handler: wsgi_handler.handler
    url: true

custom:
  wsgi:
    app: webhook.app
  pythonRequirements:
    pythonBin: python